{% set name = "phconvert" %}
{% set version = "0.9" %}
{% set sha256 = "7049ec6b57e7571988eabf7f1a3025b129c9000e873374fbb85c2d837d8a8d17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Photon-HDF5/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python >=3.5
    - setuptools
    - numpy >=1.9
    - pytables

test:
  imports:
    - phconvert

about:
  home: http://photon-hdf5.github.io/phconvert
  license: MIT
  license_file: LICENSE.txt
  summary: 'Convert and write Photon-HDF5 files.'
  description: |
    *phconvert* is a python 2 & 3 library that helps writing valid
    Photon-HDF5 <http://photon-hdf5.org/>
    files, a file format for time stamp-based single-molecule spectroscopy.
    Additionally, phconvert can convert all the common binary formats
    used in in single-molecule spectroscopy (e.g. PicoQuant .HT3,
    Becker & Hickl .SPC/.SET) to Photon-HDF5.
  doc_url: http://phconvert.readthedocs.io/
  dev_url: https://github.com/Photon-HDF5/phconvert

extra:
  recipe-maintainers:
    - harripd
    - tritemio
