{% set name = "phconvert" %}
{% set version = "0.10.1" %}
{% set sha256 = "5df1236bf9657c14bdf511c4ea73c7d82ff2c5eb76437497ea114258492ab2e2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Photon-HDF5/phconvert/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0

requirements:
  host:
    - python >={python_min}
    - setuptools >=64
    - setuptools-scm >=6.0
    - pip
  run:
    - python >={python_min}
    - numpy >=1.19
    - pytables
    - importlib_resources

test:
  requires:
    - python >={python_min}
  imports:
    - phconvert
  commands:
    - pip check
  requires:
    - pip


about:
  home: http://photon-hdf5.github.io/phconvert
  license: MIT
  license_file: LICENSE.txt
  summary: 'Convert and write Photon-HDF5 files.'
  description: |
    *phconvert* is a python 3 library that helps writing valid
    Photon-HDF5 <http://photon-hdf5.org/>
    files, a file format for time stamp-based single-molecule spectroscopy.
    Additionally, phconvert can convert all the common binary formats
    used in in single-molecule spectroscopy (e.g. PicoQuant .HT3,
    Becker & Hickl .SPC/.SET) to Photon-HDF5.
  doc_url: http://phconvert.readthedocs.io/
  dev_url: https://github.com/Photon-HDF5/phconvert

extra:
  recipe-maintainers:
    - harripd
    - tritemio
